# Generated by Django 5.2.8 on 2026-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0011_groupmembership_last_viewed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Replies'},
        ),
    ]
