# Generated by Django 5.2.8 on 2026-07-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0012_alter_comment_options_alter_reply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fund_description',
            field=models.TextField(blank=True, help_text="Detailed description of the group's fund purpose (used for 'custom' and 'emergency' types)", null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified NGO/Church account — required to create public Emergency Fundraiser campaigns'),
        ),
        migrations.AddField(
            model_name='group',
            name='purpose',
            field=models.CharField(choices=[('bereavement', 'Bereavement Fund'), ('excess', 'Insurance Excess Fund'), ('emergency', 'Emergency / Disaster Fundraiser'), ('custom', 'Custom Fund')], default='bereavement', help_text='The primary fund-pooling purpose of this group', max_length=20),
        ),
    ]
