# Generated by Django 5.2.8 on 2026-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0013_group_fund_description_group_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='verified_members_only',
            field=models.BooleanField(default=False, help_text='Only allow verified user profiles to join this group'),
        ),
    ]
