# Generated by Django 5.2.8 on 2026-07-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0014_group_verified_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('ngo', 'NGO'), ('church', 'Church/Religious Org'), ('npo', 'NPO/Charity'), ('corporate', 'Corporate/Business'), ('other', 'Other Organisation')], help_text='The type of legal entity for this organisation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official registry/registration number', max_length=100, null=True),
        ),
    ]
