# Generated by Django 5.2.8 on 2026-07-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0015_group_entity_type_group_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='group',
            name='registration_number',
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='organisation_cover_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(choices=[('ngo', 'NGO'), ('church', 'Church/Religious Org'), ('npo', 'NPO/Charity'), ('corporate', 'Corporate/Business'), ('other', 'Other Organisation')], default='ngo', max_length=50)),
                ('external_wallet_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_organisations', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='chema.organisation'),
        ),
    ]
