# Generated by Django 5.2.8 on 2026-07-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0013_group_fund_description_group_is_verified_and_more'),
        ('condolence', '0003_contribution_payment_method_contribution_transaction_and_more'),
        ('user', '0003_notification'),
        ('wallet', '0004_transaction_sender_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('bereavement', 'Bereavement'), ('excess', 'Insurance Excess'), ('emergency', 'Emergency / Disaster'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional goal. Leave blank for open-ended collection.', max_digits=10, null=True)),
                ('contributions_open', models.BooleanField(default=True)),
                ('funds_disbursed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Public campaigns appear in the global Fundraisers tab for all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, help_text='Optional end date. Contributions close after this date.', null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_campaigns', to='user.profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to='user.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_campaigns', to='chema.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('wallet', 'Wallet Balance'), ('other', 'Other')], default='wallet', max_length=50)),
                ('contribution_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional message with contribution')),
                ('contributing_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_campaign_contributions', to='user.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_group_contributions', to='chema.group')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contribution', to='wallet.transaction')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contributions', to='condolence.fundcampaign')),
            ],
            options={
                'ordering': ['-contribution_date'],
                'unique_together': {('campaign', 'contributing_member')},
            },
        ),
    ]
