# Generated by Django 5.2.8 on 2026-07-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0016_remove_group_entity_type_remove_group_is_verified_and_more'),
        ('condolence', '0004_fundcampaign_campaigncontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontribution',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_organisation_contributions', to='chema.organisation'),
        ),
        migrations.AddField(
            model_name='fundcampaign',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_campaigns', to='chema.organisation'),
        ),
        migrations.AlterField(
            model_name='campaigncontribution',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_group_contributions', to='chema.group'),
        ),
        migrations.AlterField(
            model_name='fundcampaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_campaigns', to='chema.group'),
        ),
    ]
