# Generated by Django 5.2.8 on 2026-02-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_p2p_transfers', to='wallet.wallet'),
        ),
    ]
