# Generated by Django 5.2.8 on 2026-07-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condolence', '0004_fundcampaign_campaigncontribution'),
        ('wallet', '0004_transaction_sender_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fund_campaign',
            field=models.ForeignKey(blank=True, help_text='Links this transaction to a generic FundCampaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_transactions', to='condolence.fundcampaign'),
        ),
    ]
