# Generated by Django 5.2.8 on 2026-07-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0016_remove_group_entity_type_remove_group_is_verified_and_more'),
        ('wallet', '0005_transaction_fund_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chema.organisation'),
        ),
    ]
