# Generated by Django 5.2.8 on 2026-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transaction_destination_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_channel',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('voucher', 'Voucher Cash-out')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdrawal_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
