# Generated by Django 5.2.8 on 2026-07-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0016_remove_group_entity_type_remove_group_is_verified_and_more'),
        ('user', '0004_profile_is_verified'),
        ('wallet', '0007_transaction_withdrawal_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWalletTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approvals', models.ManyToManyField(blank=True, related_name='approved_group_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('executed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_group_transfer_requests', to='wallet.transaction')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfer_requests', to='chema.group')),
                ('recipient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_wallet_transfer_requests', to='user.profile')),
                ('recipient_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_group_transfer_requests', to='wallet.wallet')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_wallet_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
