# Generated by Django 5.2.8 on 2026-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has a verified identity.'),
        ),
    ]
